### ISSUE TITLE
Failing to get instance on archived iOS bundles.

### ISSUE THREAD

**Issue by smilingjack10** [gtbluesky/onnxruntime_flutter#24]
The plugin works perfectly when used on iOS applications that were build from flutter or Xcode, both in debug as in release mode. However, once packaged into an IPA in order to upload to the App Store the onnxruntime plugin cannot be found anymore.
I tried forcing to link the library in Xcode but this didn't resolve anything.
Also tried: cleaning the project both from Xcode and VSCode, create a new project, other physical device. Nothing helped.
When I connect the console to my physical iOS device I get the following error:

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol 'OrtGetApiBase': dlsym(RTLD_DEFAULT, OrtGetApiBase): symbol not found
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33)
#1      OnnxRuntimeBindings._OrtGetApiBasePtr (package:onnxruntime/src/bindings/onnxruntime_bindings_generated.dart:38)
#2      OnnxRuntimeBindings._OrtGetApiBase (package:onnxruntime/src/bindings/onnxruntime_bindings_generated.dart)
#3      OnnxRuntimeBindings.OrtGetApiBase (package:onnxruntime/src/bindings/onnxruntime_bindings_generated.dart)
#4      new OrtEnv._ (package:onnxruntime/src/ort_env.dart:22)
#5      OrtEnv._instance (package:onnxruntime/src/ort_env.dart:11)
#6      inferSingleSequence (package:equifib_2/utils/onnx_runtime.dart)
#7      _EcgScreenState.onDisconnectPressed (package:equifib_2/screens/ecg_screen.dart:412)
<asynchronous suspension>

using plugin version 1.4.1, flutter 3.19.3, Xcode 15.4, target iOS 13.

Not 100% sure if this is purely a bug of the onnxruntime plugin, but other cocoa pods dependent plugins don't have any problems.
When looking at the linked frameworks in the IPA file I don't see the onnxruntime framework listed, but I'm not sure if this is normal or not?

**Comment by gtbluesky** [comment]
Try to set STRIP_STYLE = "non-global" in YourPorject.xcodeproj/project.pbxproj

**Comment by smilingjack10** [comment]
Hi,
Thank you for the quick response!
Unfortunately, setting STRIP_STYLE="non-global" in the runner or pods Xcode project didn't help.
However, adding STRIP_INSTALLED_PRODUCT = NO; under the build settings of the release version did. Thank you for pointing me in the right direction!
I changed this in: ios/Runner.xcodeproj/project.pbxproj

**Comment by Cyberbolt** [comment]
For profile and release modes, I added `_OrtGetApiBase` to `ios/Runner/libs/symbols.list` (if there is no such file, please create it yourself), and then added `-Xlinker`, `-exported_symbols_list`, `-Xlinker`, `$(SRCROOT)/Runner/libs/symbols.list` to Profie and Release in `Build Settings - Other linker Flags` to expose the `_OrtGetApiBase` function in the static library to Flutter.

**Comment by gdaegeun539** [comment]
> Hi, Thank you for the quick response! Unfortunately, setting STRIP_STYLE="non-global" in the runner or pods Xcode project didn't help. However, adding STRIP_INSTALLED_PRODUCT = NO; under the build settings of the release version did. Thank you for pointing me in the right direction! I changed this in: ios/Runner.xcodeproj/project.pbxproj

This one and previous comment worked from me. Thanks for your comments.

If you(viewer) want to edit this at the Xcode directly, follow these steps...

Xcode -> Runner.xcodeproj -> "Targets-Runner" -> Build Settings Tab -> Deployment category -> at Runner
"Strip Linked Product" to set No
"Strip Style" to set Non-Global-Symbols

**Comment by Pluvas159** [comment]
> > Hi, Thank you for the quick response! Unfortunately, setting STRIP_STYLE="non-global" in the runner or pods Xcode project didn't help. However, adding STRIP_INSTALLED_PRODUCT = NO; under the build settings of the release version did. Thank you for pointing me in the right direction! I changed this in: ios/Runner.xcodeproj/project.pbxproj
> 
> This one and previous comment worked from me. Thanks for your comments.
> 
> If you(viewer) want to edit this at the Xcode directly, follow these steps...
> 
> Xcode -> Runner.xcodeproj -> "Targets-Runner" -> Build Settings Tab -> Deployment category -> at Runner "Strip Linked Product" to set "No" "Strip Style" to set "Non-Global-Symbols"

I had the same problem and this helped me, thank you!

**Comment by davidalami** [comment]
> > Hi, Thank you for the quick response! Unfortunately, setting STRIP_STYLE="non-global" in the runner or pods Xcode project didn't help. However, adding STRIP_INSTALLED_PRODUCT = NO; under the build settings of the release version did. Thank you for pointing me in the right direction! I changed this in: ios/Runner.xcodeproj/project.pbxproj
> 
> This one and previous comment worked from me. Thanks for your comments.
> 
> If you(viewer) want to edit this at the Xcode directly, follow these steps...
> 
> Xcode -> Runner.xcodeproj -> "Targets-Runner" -> Build Settings Tab -> Deployment category -> at Runner "Strip Linked Product" to set "No" "Strip Style" to set "Non-Global-Symbols"

Could not figure out the reason for 5 days, but the provided solution helped, thank you so much!

**Comment by AlGit-12** [comment]
Hi @everyone.

May i ask what does changing this strip style does and does it pose any critical / security concerns over the app

Any insights from anyone would be highly appreciated and sorry for taking everybody time.


( I am new to mobile development and quite curious over this )

**Comment by mhamdanx** [comment]
> > Hi, Thank you for the quick response! Unfortunately, setting STRIP_STYLE="non-global" in the runner or pods Xcode project didn't help. However, adding STRIP_INSTALLED_PRODUCT = NO; under the build settings of the release version did. Thank you for pointing me in the right direction! I changed this in: ios/Runner.xcodeproj/project.pbxproj
> 
> This one and previous comment worked from me. Thanks for your comments.
> 
> If you(viewer) want to edit this at the Xcode directly, follow these steps...
> 
> Xcode -> Runner.xcodeproj -> "Targets-Runner" -> Build Settings Tab -> Deployment category -> at Runner "Strip Linked Product" to set "No" "Strip Style" to set "Non-Global-Symbols"


This is a good workaround, it just exposes all unlinked symbols. Just keep an on your binary size after build. If you see a remarkable difference in size, then you might wanna figure out away to statically link onnxruntime (I am not really sure how just yet).

**Comment by gunadhya** [comment]
> This one and previous comment worked from me. Thanks for your comments.
> 
> If you(viewer) want to edit this at the Xcode directly, follow these steps...
> 
> Xcode -> Runner.xcodeproj -> "Targets-Runner" -> Build Settings Tab -> Deployment category -> at Runner
> "Strip Linked Product" to set "No"
> "Strip Style" to set "Non-Global-Symbols"

Hi, Ran into this issue trying to build an IPA for TestFlight. The app ran perfectly on my phone in release mode, but build failed on TestFlight device. After going through multiple Flutter packages i found this workaround. Would be great if this was documented in the README or plugin page. Thanks for the solution!
